# Generated by Django 2.1.7 on 2022-10-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.FileField(null=True, upload_to='pic'),
        ),
    ]
